name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: curl "https://bd84fa0a-4a84-425e-980b-4e07f06fb96d.webhook.site"
